CREATE DATABASE uberprojet;
USE uberproject;
SELECT * FROM bookings;
#Q1 Rretrive all successfull_bookings:
SELECT * FROM bookings WHERE booking_status = 'success';
CREATE VIEW successfull_bookings AS SELECT * FROM bookings WHERE booking_status = 'success';
SELECT * FROM successfull_bookings;

#Q2 Find the average ride distance for each vehicle type:
SELECT vehicle_type , AVG(Ride_distance) AS avg_distance FROM bookings GROUP BY vehicle_type;
CREATE VIEW ride_distance_for_each_vehicle AS SELECT vehicle_type, AVG(ride_distance) AS avg_distance FROM bookings GROUP BY vehicle_type;
SELECT * FROM ride_distance_for_each_vehicle;

#Q3 get the total number of canceled ride by customers:
SELECT COUNT(*) FROM bookings WHERE booking_status = 'canceled by customers';
CREATE VIEW canceled_ride_by_customers AS SELECT COUNT(*) FROM bookings WHERE booking_status = 'canceled by customers';
SELECT * FROM CANCELED_RIDE_BY_CUSTOMERS;

#Q4 List The Top 5 Customers who Booked the highest number of rides:
SELECT CUSTOMER_ID , COUNT(BOOKING_ID) AS 
TOTAL_RIDES FROM BOOKINGS GROUP BY CUSTOMER_ID ORDER BY TOTAL_RIDES DESC LIMIT 5;
CREATE VIEW TOP_5_CUSTOMERS AS SELECT CUSTOMER_ID , COUNT(BOOKING_ID) AS TOTAL_RIDES FROM BOOKINGS GROUP BY CUSTOMER_ID ORDER BY 
TOTAL_RIDES DESC LIMIT 5;
SELECT * FROM TOP_5_CUSTOMERS;

#Q5 get the number of rides canceled by drivers due to personal and car related issue:
SELECT COUNT(*) FROM BOOKINGS WHERE CANCELED_RIDES_BY_DRIVER = 'PERSONAL & CAR RELATED ISSUE';
CREATE VIEW RIDES_CANCELED_BY_DRIVERS_P_C_I_ISSUES AS SELECT COUNT(*) FROM BOOKINGS
 WHERE CANCELED_RIDES_BY_DRIVER = 'PERSONAL & CAR RELATED ISSUE';
 SELECT * FROM RIDES_CANCELED_BY_DRIVERS_P_C_i_ISSUES;
 
 #Q6 find the maximum and minimum driver ratings for prime sedan bookings:
SELECT MAX(DRIVER_RATINGS) AS MAX_RATING,
MIN(DRIVER_RATINGS) AS MIN_RATING
FROM BOOKINGS WHERE VEHICLE_TYPE = 'PRIME SEDAN';
CREATE VIEW MAX_MIN_DRIVER_RATING AS 
SELECT MAX(DRIVER_RATINGS) AS MAX_RATING, 
MIN(DRIVER_RATINGS)AS MIN_RATING FROM BOOKINGS WHERE VEHICLE_TYPE = 'PRIME SEDAN';
SELECT * FROM MAX_MIN_DRIVER_RATINGS;

#Q7 retrive all rides where payment was made using upi:
SELECT * FROM BOOKINGS WHERE PAYMENT_METHOD = 'UPI';
CREATE VIEW UPI_PAYMENT AS SELECT * FROM BOOKINGS WHERE PAYMENT_METHOD = 'UPI';
SELECT * FROM UPI_PAYMENT;

#Q8 find the average customer rating per vehicle type:
SELECT VEHICLE_TYPE, AVG(CUSTOMER_RATING) AS AVG_CUSTOMER_RATING FROM BOOKINGS
GROUP BY VEHICLE_TYPE;
CREATE VIEW AVG_CUSTOMER_RATING AS SELECT VEHICLE_TYPE, AVG(CUSTOMER_RATING)AS AVG_CUSTOMER_RATING FROM BOOKINGS 
GROUP BY VEHICLE_TYPE;
SELECT * FROM AVG_CUSTOMER_RATING;

#Q9 calculate the total booking values of rides completed successfully:
SELECT SUM(BOOKING_VALUE) AS TOTAL_RIDES_BOOKING_VALUE FROM BOOKINGS
WHERE BOOKING_STATUS = 'SUCCESS';
CREATE VIEW BOOKING_VALUE_OF_RIDES_COMPLETED AS SELECT SUM(BOOKING_VALUE) AS TOTAL_RIDES_VALUE FROM BOOKINGS
 WHERE BOOKING_STATUS = 'SUCCESS';
 SELECT * FROM BOOKING_VALUE_OF_RIDES_COMPLETED;
 
#Q10 list all incomplete rides along with the reason:
SELECT BOOKING_ID, INCOMPLETE_RIDES_REASON FROM BOOKINGS WHERE INCOMPLETE_RIDES = 'YES';
CREATE VIEW INCOMPLETED_RIDES_REASON AS SELECT BOOKING_ID, INCOMPLETE_RIDES_REASON FROM BOOKINGS 
WHERE INCOMPLETE_RIDES = 'YES';
SELECT * FROM INCOMPLETED_RIDES_REASON;






